One to Many CRUD operation/Worker_Project/Models/ViewModel/WorkerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Worker_Project.Custom_Attribute;

namespace Worker_Project.Models.ViewModel
{
    public class WorkerViewModel
    {
        public int WorkerId { get; set; }
        [Required, Display(Name = "Worker Name")]
        public string WorkerName { get; set; }
        [Required, Column(TypeName = "money"), ValidSalary(ErrorMessage ="Salary must be >= 5000")]
        public decimal Salary { get; set; }
        
        public HttpPostedFileBase Picture { get; set; }
        [Required, Display(Name = "Type Id")]
        public int TypeId { get; set; }
    }
}

One to Many CRUD operation/Worker_Project/Models/Worker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worker_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Worker_Project.Models.Annotation;

    [MetadataType(typeof(WorkerAnnotation))]
    public partial class Worker
    {
        public int WorkerId { get; set; }
        public string WorkerName { get; set; }
        public decimal Salary { get; set; }
        public string Picture { get; set; }
        public int TypeId { get; set; }
    
        public virtual WorkerType WorkerType { get; set; }
    }
}

One to Many CRUD operation/Worker_Project/Models/WorkerType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worker_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Worker_Project.Models.Annotation;

    [MetadataType(typeof(WorkertypeAnn))]
    public partial class WorkerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkerType()
        {
            this.Workers = new HashSet<Worker>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Workers { get; set; }
    }
}

One to Many CRUD operation/Worker_Project/Controllers/WorkersController.cs
using Worker_Project.Models;
using Worker_Project.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Worker_Project.Controllers
{
    [Authorize]
    public class WorkersController : Controller
    {
        // GET: Workers
        readonly WorkerDbContext db = new WorkerDbContext();
        public ActionResult Index()
        {
            return View(db.Workers.ToList());
        }
        public ActionResult Create()
        {
            ViewBag.TypeList = db.WorkerTypes.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(WorkerViewModel w)
        {
            if (ModelState.IsValid)
            {

                var f = Server.MapPath("~/UploadImages/");
                string file = Guid.NewGuid() + Path.GetExtension(w.Picture.FileName);
                w.Picture.SaveAs( f+ file);
                var pic = new Worker {WorkerName = w.WorkerName, Salary = w.Salary, Picture = file, TypeId = w.TypeId };
                db.Workers.Add(pic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeList = db.WorkerTypes.ToList();
            return View(w);
        }
        public ActionResult Edit(int id)
        {
            var data = db.Workers.First(x => x.WorkerId == id);
            ViewBag.TypeList = db.WorkerTypes.ToList();
            return View(new WorkerViewModel 
                        {WorkerId=data.WorkerId,
                        WorkerName=data.WorkerName,
                        Salary=data.Salary,
                        TypeId=data.TypeId });
        }
        [HttpPost]
        public ActionResult Edit(WorkerViewModel w)
        {
            if (ModelState.IsValid)
            {
                var wo = db.Workers.First(x => x.WorkerId == w.WorkerId);
                if(w.Picture!= null && w.Picture.FileName != "")
                {
                    var f = Server.MapPath("~/UploadImages/");
                    string file = Guid.NewGuid() + Path.GetExtension(w.Picture.FileName);
                    w.Picture.SaveAs(f + file);
                    wo.Picture = file;
                }
                wo.WorkerName = w.WorkerName;
                wo.Salary = w.Salary;
                wo.TypeId = w.TypeId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeList = db.WorkerTypes.ToList();
            return View(w);
        }
        public ActionResult Delete(int id)
        {
            
            return View(db.Workers.First(x => x.WorkerId == id));
        }
        [HttpPost]
        public ActionResult Delete(Worker w)
        {
            db.Entry(w).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

One to Many CRUD operation/Worker_Project/Views/Workers/Create.cshtml
@model Worker_Project.Models.ViewModel.WorkerViewModel
@{
    ViewBag.Title = "Create Worker";
}

<div class="row my-3">
    <div class="col-10 offset-2">
        <a href="@Url.Action("Index","Workers")" class="btn btn-link">Back to list</a>
    </div>
</div>
<div class="row">
    <div class="col-10 offset-2">
        <h2>Create New Worker</h2>
    </div>
</div>
@using (Html.BeginForm("Create", "Workers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row mb-1">
        @Html.LabelFor(x => x.WorkerName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.WorkerName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.WorkerName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.Salary, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Salary, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Salary, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.TypeId, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.TypeId, new SelectList(ViewBag.TypeList, "TypeId", "TypeName"), "---Select One---", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.TypeId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-2">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
}
@section scripts{

    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $.validator.addMethod("salary", function (value, element, params) {
            if (value) {
                if (Number(value) < 5000)
                    return false;
                else return true;
            }
        });
        $.validator.unobtrusive.adapters.addBool("salary");
    </script>

}

One to Many CRUD operation/Worker_Project/Views/Workers/Delete.cshtml
@model Worker_Project.Models.Worker
@{
    ViewBag.Title = "Delete Worker";
}

<div class="row my-3">
    <div class="col-10 offset-2">
        <a href="@Url.Action("Index","Workers")" class="btn btn-link">Back to list</a>
    </div>
</div>

<div class="row my-3">
    <div class="col-10 offset-2">
        <h2>Delete Worker</h2>
    </div>
</div>
@using (Html.BeginForm("Delete", "Workers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.WorkerId)

    <div class="row mb-1">
        <div class="col-4 offset-2">
            <img class="rounded" src="~/UploadImages/@Html.DisplayFor(x=>x.Picture)" alt="Alternate Text" width="70" height="70" />
        </div>
    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.WorkerName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.WorkerName, new { @class = "form-control" })
        </div>

    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.Salary, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Salary, "{0:.00}", new { @class = "form-control" })
        </div>

    </div>

    <div class="row mb-1">
        @Html.LabelFor(x => x.WorkerType.TypeName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.WorkerType.TypeName, new { @class = "form-control" })
        </div>

    </div>
    <div class="row">
        <div class="col-10 offset-2">
            <button type="submit" class="btn btn-warning">Delete</button>
        </div>
    </div>
}

One to Many CRUD operation/Worker_Project/Views/Workers/Edit.cshtml
@model Worker_Project.Models.ViewModel.WorkerViewModel
@{
    ViewBag.Title = "Edit Worker";
}

<div class="row my-3">
    <div class="col-10 offset-2">
        <a  href="@Url.Action("Index","Workers")" class="btn btn-link">Back to list</a>
    </div>
</div>
<div class="row my-3">
    <div class="col-10 offset-2">
        <h2>Edit Worker Data</h2>
    </div>
</div>
@using (Html.BeginForm("Edit", "Workers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.WorkerId)

    <div class="row mb-1">
        @Html.LabelFor(x => x.WorkerName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.WorkerName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.WorkerName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.Salary, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Salary, "{0:.00}", new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Salary, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">
        <span class="col-2 col-form-label text-end">Type Name </span>
        <div class="col-4">
            @Html.DropDownListFor(x => x.TypeId, new SelectList(ViewBag.TypeList, "TypeId", "TypeName"), "---Select One---", new { @class = "form-select" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.TypeId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-2">
            <button type="submit" class="btn btn-outline-warning">Update</button>
        </div>
    </div>
}
@section scripts{

    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>
        $.validator.addMethod("salary", function (value, element, params) {
            if (value) {
                if (Number(value) < 5000)
                    return false;
                else return true;
            }
        });
        $.validator.unobtrusive.adapters.addBool("salary");
    </script>
}

One to Many CRUD operation/Worker_Project/Views/Workers/Index.cshtml
@model IEnumerable<Worker_Project.Models.Worker>
@{
    ViewBag.Title = "Worker Index";
}

<div class="row">

    <div class="col-12">
        <h2>Worker Type</h2>
        <div class="d-flex justify-content-end mb-1">
            <a href="@Url.Action("Create","Workers")" class="btn btn-sm btn-outline-primary">Create Worker</a>
        </div>
    </div>
    <div class="col-12">

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Picture</th>
                    <th>Worker Name</th>
                    <th>Basic Salary</th>
                    <th>Type Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var w in Model)
                {
                    <tr>
                        <td><img class="rounded" src="/UploadImages/@w.Picture" alt="@w.WorkerName" width="70" height="70" /></td>
                        <td>@w.WorkerName</td>
                        <td>@Html.DisplayFor(x => w.Salary, "{0:0.00}")</td>
                        <td>@w.WorkerType.TypeName</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Workers", new { id = w.WorkerId }, new { @class = "btn btn-link" })
                            @Html.ActionLink("Delete", "Delete", "Workers", new { id = w.WorkerId }, new { @class = "btn btn-link text-danger" })
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>