One to Many CRUD operation/Worker_Project/Controllers/WorkerTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Worker_Project.Models;

namespace Worker_Project.Controllers
{
    [Authorize]
    public class WorkerTypesController : Controller
    {
        // GET: WorkerTypes
        readonly WorkerDbContext db = new WorkerDbContext();
        public ActionResult Index()
        {
            return View(db.WorkerTypes.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(WorkerType wt)
        {
            if (ModelState.IsValid)
            {
                db.WorkerTypes.Add(wt);
                db.SaveChanges();
                return PartialView("_success");
            }
            return PartialView("_failed");
        }
        public ActionResult Edit(int id)
        {
            
            return View(db.WorkerTypes.First(x=>x.TypeId==id));
        }
        [HttpPost]
        public ActionResult Edit(WorkerType wt)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wt).State=System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wt);
        }
        public ActionResult Delete(int id)
        {
            return View(db.WorkerTypes.First(x => x.TypeId == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            var data = new WorkerType { TypeId = id };
            db.Entry(data).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
           
        }
    }
}

One to Many CRUD operation/Worker_Project/Views/WorkerTypes/Create.cshtml
@model Worker_Project.Models.WorkerType
@{
    ViewBag.Title = "Create WorkerType";
}


<div class="row">
    <div class="col-10 offset-2 mb-4">
        <h2>Create New Worker Type</h2>
    </div>
</div>
<div class="row">
    <div class="col-12" id="popup">

    </div>
</div>
@using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "popup", OnSuccess = "success" }))
{
    <div class="row mb-1">
        @Html.LabelFor(x => x.TypeName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.TypeName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.TypeName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
    <div class="row mb-1">

        <div class="col-4 offset-2">
            <a href="@Url.Action("Index","WorkerTypes")" class="btn btn-link">Back</a>
        </div>
    </div>
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function success() {
            $("#form0").trigger("reset");
        }
    </script>
}

One to Many CRUD operation/Worker_Project/Views/WorkerTypes/Delete.cshtml
@model Worker_Project.Models.WorkerType
@{
    ViewBag.Title = "Delete WorkerType";
}

<div class="row my-3">
    <div class="col-12">
        <a title="Back to List" href="@Url.Action("Index","WorkerTypes")" class="btn btn-link"></a>
    </div>
</div>
<div class="row my-3">
    <div class="col-10 offset-2">
        <h2>Delete Worker Type</h2>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.TypeId)
    <div class="row mb-1">
        @Html.LabelFor(x => x.TypeName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.TypeName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.TypeName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-2">
            <button type="submit" class="btn btn-outline-danger">Delete</button>
        </div>
    </div>
}

One to Many CRUD operation/Worker_Project/Views/WorkerTypes/Edit.cshtml
@model Worker_Project.Models.WorkerType
@{
    ViewBag.Title = "Edit WorkerType";
}

<div class="row my-3">
    <div class="col-12">
        <a title="Back to List" href="@Url.Action("Index","WorkerTypes")" class="btn btn-link" ></a>
    </div>
</div>
<div class="row my-3">
    <div class="col-10 offset-2">
        <h2>Edit Worker Type</h2>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.HiddenFor(x => x.TypeId)
    <div class="row mb-1">
        @Html.LabelFor(x => x.TypeName, new { @class = "col-form-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.TypeName, new { @class = "form-control" })
        </div>
        <div class="col-4">
            @Html.ValidationMessageFor(x => x.TypeName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-10 offset-2">
            <button type="submit" class="btn btn-outline-warning">Update</button>
        </div>
    </div>
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

One to Many CRUD operation/Worker_Project/Views/WorkerTypes/Index.cshtml
@model IEnumerable<Worker_Project.Models.WorkerType>
@{
    ViewBag.Title = "Index WorkerType";
}

<div class="row">

    <div class="col-12">
        <h2>Worker Type</h2>
        <div class="d-flex justify-content-end mb-1">
            <a href="@Url.Action("Create","WorkerTypes")" class="btn btn-primary">Create</a>
        </div>
    </div>
    <div class="col-12">

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Type ID</th>
                    <th>Type Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var w in Model)
                {
                    <tr>
                        <td>@w.TypeId</td>
                        <td>@w.TypeName</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "WorkerTypes", new { id = w.TypeId }, new { @class = "btn btn-link" })
                            @Html.ActionLink("Delete", "Delete", "WorkerTypes", new { id = w.TypeId }, new { @class = "btn btn-link text-danger" })
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>